### ISSUE TITLE
Build error: "By not providing "Findyak.cmake" in CMAKE_MODULE_PATH..."

### ISSUE THREAD

**Issue by yyxr75** [ros-industrial/yak_ros#19]
Hi there,
Error came up when I tried to build this in my ROS1 workspace.
I did what the 'readme' says, clone this repository into mycatkin_ws/src/
then I ran 'catkin build'
the error is:

  By not providing "Findyak.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "yak", but
  CMake did not find one.

  Could not find a package configuration file provided by "yak" with any of
  the following names:

    yakConfig.cmake
    yak-config.cmake

  Add the installation prefix of "yak" to CMAKE_PREFIX_PATH or set "yak_DIR"
  to a directory containing one of the above files.  If "yak" provides a
  separate development package or SDK, be sure it has been installed.

What should I do then?
Thx a lot

**Comment by schornakj** [comment]
It looks like you're not building Yak, which is the underlying TSDF library that `yak_ros` uses. You will need to clone Yak into your workspace and install its dependencies before you can build `yak_ros`. It has a separate set of installation instructions, [which can be found here](https://github.com/ros-industrial/yak).

**Comment by yyxr75** [comment]
> It looks like you're not building Yak, which is the underlying TSDF library that `yak_ros` uses. You will need to clone Yak into your workspace and install its dependencies before you can build `yak_ros`. It has a separate set of installation instructions, [which can be found here](https://github.com/ros-industrial/yak).

Thank you a lot,
I tried to build and install 'yak' the project
I build it on CUDA 9.0 but error shows:

> [  5%] Building NVCC (Device) object CMakeFiles/yak.dir/src/cuda/yak_generated_tsdf_volume.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_20'
CMake Error at yak_generated_tsdf_volume.cu.o.cmake:220 (message):
  Error generating
  /home/yang/catkin_ws/src/yak/build/CMakeFiles/yak.dir/src/cuda/./yak_generated_tsdf_volume.cu

It seems I need to comment some config in some files
I was mostly told by the  blog from [webs](https://www.cnblogs.com/houjun/p/9885847.html) that I should comment something in Makefile.config
but I can't find this file.

**Comment by schornakj** [comment]
Strictly speaking that's a Yak issue rather than a `yak_ros` issue, since it's an error while compiling the Yak CUDA libraries. I made [a new issue on the Yak issues page](https://github.com/ros-industrial/yak/issues/25) and I'll post further comments over there.

You can close this issue if your original question has been resolved.
