### ISSUE TITLE
Create a separate yak_ros2 repository

### ISSUE THREAD

**Issue by schornakj** [ros-industrial/yak_ros#33]
It should be easier to manage separate ROS1/ROS2 versions of this package if they're in separate repositories, vs. two different branches of the same repository.

edit: Related Discourse discussion: https://discourse.ros.org/t/ros2-transition-strategy/9154/6

**Comment by Levi-Armstrong** [comment]
I prefer the two separate repository approach.

**Comment by schornakj** [comment]
@Levi-Armstrong When you get a chance, could you make `ros-industrial/yak_ros2` and add me as a maintainer?

After that, the major task is splitting up the ROS1 and ROS2 portions of this repo, which currently both live in the same branch.

There are also some WIP ROS2 updates in #22 that should be included in the ROS2 package.

**Comment by gavanderhoorn** [comment]
> @Levi-Armstrong When you get a chance, could you make `ros-industrial/yak_ros2` and add me as a maintainer?

I'm not @Levi-Armstrong, but I can also create repositories.

I've created `yak_ros2` and restructured the ACLs a bit. You're admin on all three repos, and team maintainer on both teams.

**Comment by schornakj** [comment]
@gavanderhoorn Thank you very much!

**Comment by schornakj** [comment]
Closing since a separate repo was created and an PR with an initial port has been submitted there.
